# Generated by Django 5.0 on 2023-12-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('STOPPED', 'STOPPED'), ('REPAID', 'REPAID')], default='ACTIVE', max_length=100),
        ),
    ]
