# Generated by Django 5.0 on 2023-12-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repayment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='emi_amount',
        ),
    ]
