# Generated by Django 5.0 on 2023-12-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment', '0002_remove_payment_emi_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_paid',
            field=models.IntegerField(default=0),
        ),
    ]
